version: '3'
services:
  bench:
    build:
      context: .
      dockerfile: ./docker/bench/Dockerfile
      args:
        GIT_URL: https://github.com/isucon/isucon7-qualify.git
    image: isucon7-qualifier-bench
    depends_on:
      - web
    networks:
      - frontend
  web:
    build:
      context: ./docker/web-php
      args:
        GIT_URL: https://github.com/isucon/isucon7-qualify.git
    image: isucon7-qualifier-web:nginx-php
    networks:
      - frontend
      - backend
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./isucon7-qualify/webapp:/home/isucon/isubata/webapp
      - ./.data/var/log/nginx:/var/log/nginx
  app:
    build:
      context: ./docker/app/php
      args:
        GIT_URL: https://github.com/isucon/isucon7-qualify.git
    image: isucon7-qualifier-app:php
    networks:
      - backend
    depends_on:
       - db
       - redis
    ports:
      - "5000"
    environment:
      ISUBATA_DB_USER: isucon
      ISUBATA_DB_PASSWORD: isucon
      ISUBATA_DB_HOST: db
    volumes:
      - ./isucon7-qualify/webapp:/home/isucon/isubata/webapp
  db:
    build:
      context: ./docker/db
      args:
        GIT_URL: https://github.com/isucon/isucon7-qualify.git
    image: isucon7-qualifier-db
    ports:
      - "3306:3306"
    networks:
      - backend
    command: ["--character-set-server=utf8mb4"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: isubata
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    volumes:
      - ./.data/var/log/mysql:/var/log/mysql
  redis:
    image: redis:7.0.2
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  frontend:
  backend:
